# Change these first
owner: merlinfuchs # Your GitHub organization or username, where this repository lives
repo: xenon-uptime # The name of this repository

sites:
  - name: Xenon Website
    url: https://xenon.bot/
  - name: Xenon Wiki
    url: https://wiki.xenon.bot/

status-website:
  cname: status.xenon.bot
  # baseUrl: /xenon-uptime
  logoUrl: https://xenon.bot/logo-small.png
  favicon: https://xenon.bot/logo-small.png
  name: Xenon Status
  introTitle: "**Xenon** is the easiest way to backup, archive, copy, or clown your own Discord server."
  introMessage: This page shows the status and uptime of Xenon and the related services. If you are looking for the Xenon website click [here](https://xenon.bot)!
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://xenon.bot


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
